# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QueueIt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QueueIt

  # Our pods
  pod 'QueueITLibrary', '~>3.0.10'
end
