# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'QueueIt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QueueIt

  # Our pods
  pod 'poc-1-QueueITLibrary', :git => "https://github.com/queueit/ios-webui-sdk.git", :branch => "poc-1", :tag => "3.0.10.1"
end
